FROM docker.io/blackdex/rust-musl:x86_64-musl-stable-1.91.0 AS build

COPY . /home/rust/src

# If you want to use PostgreSQL v15 add and uncomment the following ENV
# ENV PQ_LIB_DIR="/usr/local/musl/pq15/lib"

RUN cargo build --release

FROM scratch

WORKDIR /
COPY --from=build /home/rust/src/target/x86_64-unknown-linux-musl/release/my_tracy_musl .

CMD ["/my_tracy_musl"]

